export {
  supabase,
  supabaseAdmin,
  getStudents,
  getStudentById,
  getStudentByUserId,
  createStudent,
  getTeams,
  getTeamById,
  createTeam,
  getParticipantApplications,
  getParticipantApplicationById,
  getParticipantApplicationByStudentId,
  getMentorApplications,
  getMentorApplicationById,
  getMentorApplicationByStudentId,
  getJudgeApplications,
  getJudgeApplicationById,
  getJudgeApplicationByStudentId,
  getRatings,
  getRatingById,
  getRatingsByApplicationId,
  getStudentWithApplications,
  getApplicationByStudentId,
  getApplicationsByTypeAndStatus,
  getApplicationStats,
  getStudentWithDetails,
} from "./supabase";

export type { Database } from "./supabase-types";
